### ISSUE TITLE
Document how to enable codecov integration

### ISSUE THREAD

**Issue by sverhoeven** [abelsiqueira/COPIERTemplate.jl#150]
### Description

In the generated project the README.md has a badge for [code](https://about.codecov.io/) but it says unknown. How can I enable the badge so it reports the code coverage percentage? 

Would be nice to have a section in the https://abelsiqueira.com/COPIERTemplate.jl/stable/10-full-guide/ that mentions codecov and how to enable it.

### Checks

- [X] There is not an [existing issue](https://github.com/abelsiqueira/COPIERTemplate.jl/issues) with the same question
- [X] I have read the [contributing guide](https://github.com/abelsiqueira/COPIERTemplate.jl/blob/main/docs/src/contributing.md)
- [X] I agree with the [code of conduct](https://github.com/abelsiqueira/COPIERTemplates.jl/blob/main/CODE_OF_CONDUCT.md)

**Comment by sverhoeven** [comment]
I needed to add `token: ${{ secrets.CODECOV_TOKEN }}` to the test workflow for the codecov.io website to show coverage.

**Comment by abelsiqueira** [comment]
Duplicate of #101

**Comment by abelsiqueira** [comment]
Done in #208
