### ISSUE TITLE
Use `Julia-actions/cache` uniformly

### ISSUE THREAD

**Issue by suvayu** [abelsiqueira/COPIERTemplate.jl#53]
I'm getting these in [CI](https://github.com/TulipaEnergy/TulipaIO.jl/actions/runs/8737667282):

> [julia-buildpkg] Caching of the julia depot was not detected
Consider using `julia-actions/cache` to speed up runs https://github.com/julia-actions/cache. To ignore, set input `ignore-no-cache: true` 

I guess now we don't need to rummage through docs how to do it correctly?

**Comment by abelsiqueira** [comment]
`Julia-actions/cache` uses the `actions/cache` internally. Sometimes we use one or the other or none. We should change to use `Julia-actions/cache` in all places. I will update the title.

**Comment by abelsiqueira** [comment]
@allcontributors please add @suvayu for bug
