### ISSUE TITLE
Add funding information

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/COPIERTemplate.jl#56]
Funding from the eScience Center

**Comment by abelsiqueira** [comment]
@allcontributors please add @nlesc for financial

**Comment by abelsiqueira** [comment]
@egpbos, can you help with me with this info? Is there a phrase to use for Software Sustainability projects?

**Comment by egpbos** [comment]
Good question, I'm not aware we ever did this. I don't have a strong opinion myself, I would say that just mentioning that we made it is enough. I personally like the way you did it in the PR. I personally would have done something like at the bottom of this readme: https://github.com/xenon-middleware/xenon?tab=readme-ov-file#legal Copyright NLeSC + License info in one go. But I wouldn't use a specific Software Sustainability Project mention, that's internal, nobody outside NLeSC cares :)

**Comment by abelsiqueira** [comment]
Hum, good to know. On the copyright notice, I've actually started this outside the eScience and hope to keep working on it after the funds are gone, so I'm not sure how to reflect that. What do you suggest?

**Comment by egpbos** [comment]
You could in theory mention it specifically like "Copyright Abel & NLeSC"... But note that you don't have to explicitly mention anything about copyright. Copyright applies automatically.

Just FYI, in the NLs, copyright of work done as part of your job always is owned by your employer (that applies also e.g. to papers for researchers at unis). I once looked into what I thought was the grey area of things that you do as a hobby side project. IANAL, YMMV, of course, but my conclusion was that when such side-projects are the same kind of work as you do for your boss (even for instance when you did it outside of formal working hours) the employer can still claim copyright. There is some jurisprudence on this, iirc, of people who did this and then got sued successfully by their (probably, at that stage, former) employers.

I'm not going to send any lawyers after you ;) For permissive open source projects, I feel like it is less relevant anyway (anyone can just fork and run with it). What I think is actually relevant is to mention contributors for credit (like you do nicely) and for users to make clear who/where to go to for support.

**Comment by abelsiqueira** [comment]
Hum, thanks for the info, that's good to know.

**Comment by abelsiqueira** [comment]
Done in #178
